services:
  jedi_planner_db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: developer123
      POSTGRES_DB: jedi_planner
    ports:
      - "5432:5432"
    volumes:
      - jedi_planner_db:/var/lib/postgresql
      - jedi_planner_db_data:/var/lib/postgresql/datas

  flyway:
    image: flyway/flyway
    depends_on:
      - jedi_planner_db
    volumes:
      - ./migrations:/flyway/sql
    command: -url=jdbc:postgresql://jedi_planner_db:5432/jedi_planner -user=developer -password=developer123 migrate

  sonarqube:
    image: sonarqube:lts-community
    restart: always
    depends_on:
      - sonar_db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonar_db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    ports:
      - "9001:9000"
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_temp:/opt/sonarqube/temp

  sonar_db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - sonar_db:/var/lib/postgresql
      - sonar_db_data:/var/lib/postgresql/datas

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_temp:
  sonar_db:
  sonar_db_data:
  jedi_planner_db:
  jedi_planner_db_data: