services:
  jedi_oracle19:
    image: oracle/database:19.3.0-ee
    restart: always
    environment:
      ORACLE_PWD: oracle123
    ports:
      - "1523:1521"

#  jedi_planner_db:
#    image: postgres:17.5
#    restart: always
#    environment:
#      POSTGRES_USER: jedi
#      POSTGRES_PASSWORD: jedi123
#      POSTGRES_DB: jedi_planner
#    ports:
#      - "5434:5432"
#    volumes:
#      - jedi_planner_db:/var/lib/postgresql
#      - jedi_planner_db_data:/var/lib/postgresql/datas

  flyway:
    image: flyway/flyway
    depends_on:
      - jedi_oracle19
    volumes:
      - ./migrations:/flyway/sql
    command: -url=jdbc:oracle:thin:@//jedi_oracle19:1521/ORCLPDB1 -user=developer -password=developer123 migrate

  sonarqube:
    image: sonarqube:lts-community
    restart: always
    depends_on:
      - sonar_db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonar_db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    ports:
      - "9001:9000"
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_temp:/opt/sonarqube/temp

  sonar_db:
    image: postgres:17.5
    restart: always
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - sonar_db:/var/lib/postgresql
      - sonar_db_data:/var/lib/postgresql/datas

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_temp:
  sonar_db:
  sonar_db_data:
#  jedi_planner_db:
#  jedi_planner_db_data: