# Getting started with SonarQube
# to run: docker compose -f docker-compose-local.yml up -d
# to remove: docker compose -f docker-compose-local.yml down
# to test you can access through http://localhost:9001

services:
  jedi_planner:
    image: postgres:17.5
    restart: always
    environment:
      POSTGRES_USER: jedi
      POSTGRES_PASSWORD: jedi123
      POSTGRES_DB: jedi_planner
    volumes:
      - jedi_planner_db:/var/lib/postgresql
      - jedi_planner_db_data:/var/lib/postgresql/datas
  sonarqube:
    image: sonarqube:lts-community
    restart: always
    depends_on:
      - sonar_db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonar_db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    ports:
      - "9001:9000"
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_temp:/opt/sonarqube/temp

  sonar_db:
    image: postgres:17.5
    restart: always
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - sonar_db:/var/lib/postgresql
      - sonar_db_data:/var/lib/postgresql/datas

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_temp:
  sonar_db:
  sonar_db_data:
  jedi_planner_db:
  jedi_planner_db_data: