services:
  jedi-planner-db:
    container_name: jedi-planner-db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: developer123
      POSTGRES_DB: jedi_planner
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - jedi_planner_data:/var/lib/postgresql/data

  broker:
    image: apache/kafka:latest
    container_name: broker
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://localhost:9092,CONTROLLER://localhost:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 1
    volumes:
      - kafka_logs:/tmp/kraft-combined-logs

  flyway:
    container_name: flyway
    image: flyway/flyway
    depends_on:
      jedi-planner-db:
        condition: service_healthy
    volumes:
      - ./migrations:/flyway/sql
    command: |
      -url=jdbc:postgresql://jedi-planner-db:5432/jedi_planner -user=developer -password=developer123 migrate

  jedi-planner:
    container_name: jedi-planner
    restart: always
    depends_on:
      - jedi-planner-db
      - flyway
    environment:
      PROFILE_MODE: local
    ports:
      - "8080:8080"
    build:
      context: ./
      dockerfile: Dockerfile
    image: "jedi-planner:latest"

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8081:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
  ssh-agent:
    image: jenkins/ssh-agent

volumes:
  jedi_planner_data:
  kafka_logs:
  jenkins_home: