spring:
  application:
    name: jedi-planner
  jackson:
    property-naming-strategy: LOWER_CAMEL_CASE
  main:
    web-application-type: reactive
  cloud:
    stream:
      bindings:
        input:
          destination: tasks
          group: jedi-planner-group
        output:
          destination: tasks
      default-binder: kafka
      kafka:
        binder:
          brokers:
server:
  port: ${SERVER_PORT:8080}
