spring:
  application:
    name: jedi-planner
  jackson:
    property-naming-strategy: LOWER_CAMEL_CASE
  main:
    web-application-type: reactive
  r2dbc:
    url: r2dbc:postgresql://jedi-planner-db:5432/jedi_planner
    username: developer
    password: developer123
  graphql:
    graphiql:
      enabled: true
    websocket:
      path: /graphql
server:
  port: ${SERVER_PORT:8080}
