spring:
  r2dbc:
    url: r2dbc:postgresql://jedi-planner-db:5432/jedi_planner
    username: developer
    password: developer123
  graphql:
    graphiql:
      enabled: true
    websocket:
      path: /graphql
jwt:
  refresh-secret: a7a54ae92226a9806c78552104b2a2f57167d630ef7a0665ef40723c2832ce7eb1ce7360de218f2a6e739ec307e4c787080a250b48d12460ba0e2c86bcafaab3
  access-secret: e2926909a5c43ecea3ffa3b65fc747089755d687f401cd01e1a9372ab2d39e0700f108b7a6e739170e0cd25ef4f7bc9fdcc9b71de8d1be7e6e4490aa35d191a2
  access-token-expiration: 900000 # 15 minutes
  refresh-token-expiration: 86400000 # 24 hours
logging:
  level:
    org.springframework.r2dbc.core: DEBUG
    io.r2dbc.spi: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
file:
  upload-dir: uploads