jwt:
  refresh-secret: ${REFRESH_TOKEN_SECRET}
  access-secret: ${ACCESS_TOKEN_SECRET}
  access-token-expiration: ${ACCESS_TOKEN_EXPIRATION}
  refresh-token-expiration: ${REFRESH_TOKEN_EXPIRATION}
logging:
  level:
    org.springframework.r2dbc.core: ERROR
    io.r2dbc.spi: ERROR
    org.springframework.security: ERROR
    org.springframework.web: ERROR
file:
  upload-dir: /app/uploads